-- Seinfeld Quotes Database - PostgreSQL Version
-- Generated from Seinfeld.csv

-- Create database (run this separately as superuser if needed)
-- CREATE DATABASE seinfeld_db WITH ENCODING 'UTF8';


-- Create table
DROP TABLE IF EXISTS seinfeld_quotes CASCADE;
CREATE TABLE seinfeld_quotes (
    id SERIAL PRIMARY KEY,
    quote TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    season INTEGER NOT NULL,
    episode INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX idx_author ON seinfeld_quotes (author);
CREATE INDEX idx_season_episode ON seinfeld_quotes (season, episode);

-- Insert data

INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You look like you live with your mother!', 'Jerry', 1, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This dictionary''s no good, we need a medical dictionary! When a patient is difficult, you quone him.', 'Kramer', 1, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You made a man cry? I''ve never made a man cry. I even kicked a guy in the groin once and he didn''t cry.', 'Elaine', 1, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What do you think a hit man would charge..to rub out a couple of cats?', 'Elaine', 1, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You should do it like a band-aid -- one motion, RIGHT OFF!', 'Jerry', 2, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Levels Jerry..levels. --  I''m getting rid of all my furniture. All of it. And I''m going to build these different levels, with steps, and it''ll all be carpeted with a lot of pillows. You know, like ancient Egypt.', 'Kramer', 2, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I hate anyone who ever had a pony growing up!', 'Jerry', 2, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I cannot envision any circumstance in which I''ll ever have the opportunity to have sex again. How''s it gonna happen? I just don''t see how it could occur.', 'George', 2, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('We had a funny guy with us in Korea. A tailgunner. They blew his brains out all over the Pacific. ... There''s nothing funny about that.', 'Alton Benes(Elaines Father)', 2, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Women don''t want to see need. They want a take-charge guy. A colonel, a kaiser, a czar!', 'George', 2, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Please, don''t insult me -- no one''s a bigger idiot than me.', 'George', 2, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I lie every second of the day. My whole life is a sham.', 'George', 2, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('People don''t turn down money, it''s what separates us from the animals!', 'Jerry', 2, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It was the single most damaging experience of my life -- aside from seeing my father naked', 'George', 2, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You''re in big trouble son. Burglary, grand larceny, possession of stolen goods.. and uh, uh.. murder!', 'Kramer', 2, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('C''mon what''s the big deal... just gonna put a little concrete in the washing machine', 'Kramer', 2, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh yeah I usually sit around naked a couple hours a day. I cook naked, I clean naked, I drive naked, naked, naked, naked!', 'Elaine', 2, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Women go after doctors like men go after models -- They want someone with knowledge of the body. We just want the body', 'Jerry', 2, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The really bad thing about the heart is the sex thing. See, you gotta be careful about sex now. You get that heart pumping and suddenly, boom! Next thing you know, you got a hose coming out of your chest attached to a piece of luggage!', 'Kramer', 2, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh yeah? My friend, Bob Saccomanno, he came in here for a hernia operation.. Oh yeah, routine surgery.. now he''s sittin'' around in a chair by a window going - ''My name is Bob!''', 'Kramer', 2, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I completely skipped healthy adulthood. I went from having orgasms immediately to taking forever. You could do your taxes in the time it takes me to have an orgasm.', 'George', 2, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m an eggplant! I''m an eggplant! I''m a minstrel man!', 'George', 2, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Now you listen to me. I want details and I want them right now. I don''t have a job, I have no place to go. You''re not in the mood? Well you get in the mood!', 'George', 2, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Look, will you at least let me bring the guy over? He''s an amazing man -- He''s a Russian immigrant. He escaped the Gulag! He''s like the Sakharov of cable guys.. He''ll slow down your gas meter.. He sells slugs! -- Jerry. Slugs for the subway!', 'Kramer', 2, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah I eat the whole apple.. core, stem, seeds -- everything', 'Kramer', 2, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You ever eat the bark off of a pineapple?', 'Kramer', 2, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You walk over that table, you pick up an eggroll, you don''t say anything, you eat it, say ''thank you very much'', wipe your mouth, walk away- I give you 50 bucks.', 'Jerry', 2, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Movie hotdogs! I''d rather lick the food off the floor!', 'Elaine', 2, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t know him! -- He could be one of those people who walks around the street pricking people with pins!', 'Jerry', 2, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Are you crazy?! -- I can''t have a man touching me!', 'George', 3, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know my feelings on this-- I don''t even pay taxes!', 'Kramer', 3, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('My whole life has been a complete waste of time... and there''s so much more to go.', 'George', 3, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s the financial equivalent of a complete rectal examination.', 'Jerry', 3, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''ve driven women to lesbianism before, but never a mental institution.', 'George', 3, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I believe I referred to her personality as a potential science exhibit.', 'Elaine', 3, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I wanted to talk about how we had nothing to talk about.', 'Elaine', 3, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The library investigator''s name is actually Bookman? -- That''s amazing. That''s like an ice cream man named Cone.', 'Kramer', 3, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Let me tell you something, funny boy... You know that little stamp? The one that says New York Public Library? Well, that may not mean anything to you, but that means a lot to me. One whole helluva lot. Sure, go ahead, laugh if you want to. I''ve seen your type before -- flashy, making the scene, flaunting convention. Yeah, I know what you''re thinking... Why''s this guy making such a big stink about old library books? Let me give you a hint, junior. Maybe we can live without libraries, people like you and me.... Maybe. Sure, we''re too old to change the world. What about that kid, sitting down, opening a book right now in a branch of the local library and finding pictures of pee-pees and wee-wees in The Cat in the Hat and The Five Chinese Brothers. Doesn''t he deserve better? Look, if you think this is about overdue fines and missing books, you''d better think again. This is about that kid''s right to read a book without getting his mind warped. Or maybe that turns you on, Seinfeld... Maybe that''s how you get your kicks... You and your goodtime buddies... I''ve got a flash for you, joy boy. Partytime is over.', 'Lt. Bookman', 3, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If I am not in front of my building at 6:15 when my parents get there, they are going to put me on an aggravation installment plan that will compound with interest for decades.', 'George', 3, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, I''ve been issued a public urination pass by the city because of my condition. Unfortunately, my little brother ran out of the house with it this morning. Him and his friends are probably peeing all over the place.', 'Jerry', 3, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can''t carry a pen. I''m afraid I''ll puncture my scrotum.', 'George', 3, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You should''ve seen her face. It was the exact same look my father gave me when I told him I wanted to be a ventriloquist.', 'George', 3, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what that makes you? A baldist.', 'Jerry', 3, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I have never been so repulsed by someone mentally and so attracted to them physically at the same time. It''s like my brain is facing my penis in a chess game. And I''m letting him win.', 'Jerry', 3, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t like when a woman says, ''Make love to me'', it''s intimidating. The last time a woman said that to me, I wound up apologizing to her.', 'George', 3, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What could possess anyone to throw a party?  I mean, to have a bunch of strangers treat your house like a hotel room.', 'Jerry', 3, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('These pretzels are making me thirsty.', 'Kramer', 3, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Moving cars from one side of the street to the other don''t take no more sense than puttin'' on a pair of pants. My question to you is: who''s puttin'' your pants on?', 'Sid', 3, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t know if it was the alcohol or the ammonia, but the next thing I knew she was mopping the floor with me.', 'George', 3, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You had sex on your desk with the cleaning woman.', 'Elaine', 3, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Elaine you don''t understand. I had 103 temperature when I bought that sweater. I was so dizzy I was seeing red dots everywhere. I thought everything in the store had a red dot on it. I couldn''t distinguish one red dot from another. I couldn''t afford anything. I have nothing. I haven''t worked for a really long time. I mean look, I have no clothes, look at what I''m wearing. It''s just a little red dot.', 'George', 3, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I always get the feeling that when lesbians look at me, they''re thinking, ''That''s why I''m not a heterosexual.''', 'George', 3, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Big brokerage houses killed my father.', 'George', 3, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m not a lesbian. I hate men, but I''m not a lesbian!', 'Elaine', 3, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('His mother was a mudder... His father was a mudder.', 'Kramer', 3, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('We all want the hand. Hand is tough to get.', 'Kramer', 3, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Anyone who would laugh at a recital is probably some sort of lunatic anyway. I mean, only a sick, twisted mind could be that rude and ignorant.', 'Jerry', 3, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t have a good apartment for an intervention. The furniture, it''s very non-confrontational.', 'Jerry', 3, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You can say what you want about me, but I''ll be damned if I''m going to stand here while you insult my toothbrush.', 'Jerry', 3, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The carpet sweeper is the biggest scam perpetrated on the American public since one-hour martinizing.', 'Kramer', 3, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The guy is unconscious in a coma and you don''t have the guts to kiss his girlfriend?', 'Kramer', 3, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You wouldn''t know it to look at him, but George can bait a hook.', 'Jerry', 3, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s hard enough to meet a woman you dislike, much less like.', 'Kramer', 3, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I would really like to have sex with a tall woman.', 'George', 3, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Vandelay! Say Vandelay!', 'George', 3, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('So Biff wants to be a buff? Well, sleeping less than eighteen hours a day would be a start.', 'Jerry', 3, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hello, Ma? It''s me. Guess where I am? In the back of a limo. No, nobody died. It''s a long story, I can''t tell you now. Because I can''t. I said I can''t. If I could, I would. Would you stop it. All right, look, I''m getting off. No, I''m not telling you. How''s this - I''m never telling you. I don''t care. No. Fine. Never!', 'George', 3, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I know Jerry. He''s not a Nazi. No. He''s just neat.', 'Elaine', 3, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If you want to make a person feel better after they sneeze, you shouldn''t say ''God bless you.'' You should say ''You''re so good looking!''', 'Jerry', 3, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know they''re mentally disturbed. They should be sent to Australia.', 'Kramer', 3, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I like the button fly. That is one place on my wardrobe I do not need sharp interlocking metal teeth. It''s a mink trap down there.', 'Jerry', 3, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The appeal of the posse? Posse has tremendous appeal. Get away from the job, you camp out, you''re with friends. I mean, come on, it''s a week-long game of hide-and-go-seek on horseback.', 'Jerry', 3, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I see a parasite. A sexually depraved miscreant who is seeking only to gratify his basest and most immediate urges.', 'Old Man Looking At Painting Of Kramer', 3, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('All bald people look good in hats.', 'George', 3, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You don''t understand. A garage... I can''t even pull in there. It''s like going to a prostitute. Why should I pay, when if I apply myself, maybe I could get it for free?', 'George', 3, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You want to know why you can''t go in front first? I''ll tell you why. Because it signals a breakdown in the social order. Chaos. It reduces us to jungle law.', 'Newman', 3, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m like ice, buddy. When I don''t like you, you''ve got problems.', 'Kramer', 3, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Having the keys to Jerry''s apartment - that kept me in a fantasy world. Every time I went over to his house it was like a vacation: better food, better view, better TV, cleaner, oh, *much* cleaner. That became my reality. I ignored the squalor in my own life because I''m looking at life, you see, through Jerry''s eyes. I was living in the twilight, living in the shadows, living in the darkness... like you.', 'Kramer', 3, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What do you think Junior? You think these hands - they''ve been soaking in Ivory Liquid?', 'Kramer', 3, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('My personal acting technique is working with color. Imagining, then finding the emotional vibrational mood connected to the color. See, if you look through my scripts, you see that all my lines have a special color. So, I don''t memorize language, I memorize colors. This way I can go through red, yellow, green, blue, and you have a full palette of emotions.', 'Kramer', 4, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Seemingly, but within that basic framework there are many subtle variations only discernible to an acute observer that reflect the many moods, the many shades, the many sides of George Costanza.', 'George', 4, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Artistic integrity. Where did you come up with that? You''re not artistic and you have no integrity.', 'Jerry', 4, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You wouldn''t be here if it wasn''t for me and my helmet. I saved your life! You would be dead! Dead! You would cease to exist! You would be gone for the rest of eternity! You wouldn''t even begin to comprehend what that means!', 'Newman', 4, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yes, I admit I was speeding, but it was to save a man''s life. A close friend. An innocent person who wanted nothing more out of life than to love, to be loved, and to be a banker.', 'Newman', 4, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Why would I be insulted? I''m never insulted. You could call me baldy, dump soup on my head. Nothing insults me.', 'George', 4, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Let me see if I understand this. In other words, you held out for... less money.', 'Jerry', 4, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What are you looking at? You never seen a kid in a bubble before?', 'The Bubble Boy', 4, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s very hard being a stand-up comedian. Sometimes they don''t laugh!', 'Elaine', 4, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s crowded, the grass has big brown patches in it, they don''t rake the sand traps. Not to mention the caliber of people you have to play with!', 'Kramer', 4, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I have tremendous respect for people who work with feet. I mean, to dedicate yourself to the foot... You''re toiling in virtual anonymity.', 'George', 4, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('But officer, he threatened me. I don''t understand, that''s not right. What if it was the President of the United States, I bet you''d investigate. Well, so what? What''s the difference? I''m a comedian of the United States. And I''ll tell you, I''m under just as much pressure.', 'Jerry', 4, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, it is so sad. All your knowledge of high culture comes from Bugs Bunny cartoons.', 'Elaine', 4, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t want to be remembered. I want to be forgotten.', 'George', 4, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This whole sex thing is totally overrated. Now, the one thing you gotta be ready for is how the man changes into a completely different person five seconds after it''s over. I mean, something happens to their personality. It''s really quite astounding. It''s like they committed a crime and they want to flee the scene before the police get there.', 'Elaine', 4, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can''t take it any more! She''s drivin'' me crazy. I can''t sleep, I can''t leave the house. When I''m here I''m climbin'' the walls. Meanwhile I''m datin'' a virgin, I''m in this contest... something''s gotta give!', 'Jerry', 4, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Too bad you couldn''t do *that* for a living... You''d be very successful at it. You could sell out Madison Square Garden. Thousands of people could watch you. You could be a big star!', 'George''s Mom', 4, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I hate rental cars. Nothing ever works: the window doesn''t work, the radio doesn''t work... and it smells like a cheap hooker.', 'Jerry', 4, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You see? Never be late for a plane with a girl. ''Cuz a girl runs like a girl-- with the little steps and the arms flailing out... You wanna make this plane, you''ve gotta run like a man! Get your knees up!', 'Jerry', 4, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Look at you! You run like a girl! Run like a man! Lift your knees!', 'Kramer', 4, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You *cannot* abandon people in the middle of an airport pickup! It''s a binding social contract. We must go forward, not back.', 'George', 4, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I could have been a millionaire!! I could have been a FRAGRANCE millionaire!!!', 'Kramer', 4, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('That''s the true spirit of Christmas; people being helped by people other than me.', 'Jerry', 4, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Men can sit through the most pointless, boring movie if there''s even the slightest possibility that a woman will take her top off.', 'Elaine', 4, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Kramer goes to a fantasy camp. His whole life is a fantasy camp. People should plunk down two-thousand dollars to live like him for a week. Do nothing, fall ass-backwards into money, mooch food off your neighbors, and have sex without dating. *That''s* a fantasy camp!', 'Jerry', 4, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Would it kill you not to be so funny all the time? That''s all I''m askin''. This woman thinks I''m very funny and now you''re gonna be funny, so what am I gonna be? I''m gonna be a short bald guy with glasses who suddenly doesn''t seem so funny.', 'George', 4, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, birthdays are merely symbolic of how another year''s gone by and how little we''ve grown. No matter how desperate we are that someday a better self will emerge, each flicker of the candles on the cake we know it''s not to be. That for the rest of our sad, wretched, pathetic lives, this is who we are to the bitter end. Inevitably, irrevocably. Happy birthday? No such thing.', 'Jerry', 4, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You bad man! You very bad man! You very lazy bad man!!', 'Babu', 4, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I am going to save up every rupee. For someday, I will get back to America, and when I do, I will exact vengeance on this man. I cannot forget it. He haunts me. He is a very bad man. Very, very bad man.', 'Babu', 4, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Divorce is very difficult, especially on the kids. Of course, I''m the result of my parents having stayed together, so you never know.', 'George', 4, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Looking at cleavage is like looking at the sun. You don''t stare at it. It''s too risky. You get a sense of it and then you look away.', 'Jerry', 4, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Every day it''s something else with you. I don''t know anything about you any more. Who are you? What kind of life are you leading? Who knows what you''re doing? Maybe you''re making porno films.', 'George''s Mother', 4, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh, what''s the point? When I like them, they don''t like me, when they like me, I don''t like them. Why can''t I act with the ones I like the same way I do with the ones I don''t like?', 'George', 4, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah, I''m a great quitter. It''s one of the few things I do well. I come from a long line of quitters. My father was a quitter, my grandfather was a quitter... I was raised to give up.', 'George', 4, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I would like to dip my bald head in oil and rub it all over your body.', 'George', 4, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Because the mail never stops. It just keeps coming and coming and coming, there''s never a let-up. It''s relentless. Every day it piles up more and more and more! And you gotta get it out but the more you get it out the more it keeps coming in. And then the bar code reader breaks and it''s Publisher''s Clearing House day!', 'Newman', 4, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Why would I be a leg man? I don''t need legs. I have legs.', 'Jerry', 4, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Sometimes when I think you''re the shallowest man I''ve ever met, you somehow manage to drain a little more out of the pool.', 'Jerry', 4, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Who''s gonna turn down a Junior Mint? It''s chocolate, it''s peppermint -- it''s delicious!', 'Kramer', 4, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Produce section. Very provocative area. A lot of melons and shapes. Everyone''s squeezing and smelling...', 'Jerry', 4, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Y''know, the funny thing is, somehow I find her more appealing now... It''s like if I knew she was a lesbian when we went out, I never would''ve broken up with her.', 'George', 4, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You don''t understand what I''m up against. This is a force more powerful than anything you can imagine. Even Superman would be helpless against this kind of stench.', 'Jerry', 4, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Amazing! I drive them to lesbianism, and he brings ''em back!', 'George', 4, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('First he vomits on me. Then he burns down my father''s cabin. And now he''s taken Mona away from me.', 'Susan', 4, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Is it my imagination, or do really good-looking women walk a lot faster than everybody else?', 'George', 4, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Isosceles. You know, I love the name Isosceles. If I had a kid, I would name him Isosceles. Isosceles Kramer.', 'Kramer', 4, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This is our best model, the Cougar 9000. It''s the Rolls Royce of wheelchairs. This is like, you''re almost glad to be handicapped.', 'Wheelchair Salesman', 4, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know the message you''re sending out to the world with these sweatpants? You''re telling the world, ''I give up. I can''t compete in normal society. I''m miserable, so I might as well be comfortable.''', 'Jerry', 4, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I want to be the one person who doesn''t die with dignity.', 'George', 4, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('How''d you like it if I just pulled your heart out of your chest right now and shoved it down your throat?', 'TV Kramer (to George)', 4, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The woman had an orgasm under false pretenses. That''s sexual perjury!', 'Jerry', 5, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('They don''t have a decent piece of fruit at the supermarket. The apples are mealy, the oranges are dry... I don''t know what''s going on with the papayas!', 'Kramer', 5, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Borrowing money from a friend is like having sex. It just completely changes the relationship.', 'George', 5, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh, those are nice. Ya know, I never noticed this before. They''re smooth, creamy, delicate, yet masculine.', 'Kramer', 5, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t know what to believe. You''re eatin'' onions, you''re spottin'' dimes, I don''t know what the hell is going on!', 'Jerry', 5, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s a Commando-8, 12,000 BTU''s. It''s gonna be like a meat locker in here!', 'Jerry''s Mom', 5, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh yeah, I''ve been known to drink a beer or two, but then again, I''ve been known to do a lot of things.', 'Kramer', 5, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey, I''m telling you, the pig-man is alive. The government has been experimenting with pig-men since the 50''s.', 'Kramer', 5, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I wish there were pig-men. You get a few of those pig-men walking around, suddenly I''m looking a lot better. That way if someone wanted to fix me up they could say, ''Hey, at least he''s no pig-man.''', 'Kramer', 5, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You remember this: When you control the mail, you control information!', 'Newman', 5, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You don''t eat Oreos? The way you break ''em open and.... It''s like you''re having sex with ''em.', 'Kramer', 5, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what I would do if I was running for mayor? One of my campaign themes would be that everybody should wear nametags all the time to make the city friendlier.', 'Elaine', 5, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, a lot of people consider me small and prestigious.', 'George', 5, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I show up! I pretend I have the job. The guy''s on vacation. If I have the job, it''s fine. If I don''t have the job, by the time he comes back I''m ensconced.', 'George', 5, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I haven''t vomited in thirteen years.', 'Jerry', 5, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This woman hates me so much, I''m starting to like her.', 'George', 5, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey! I am looser than creamed corn.', 'Kramer', 5, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey, you know what would make a great coffee table book? A coffee table book about coffee tables!', 'Kramer', 5, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Ya know, I don''t get it. I''m not allowed to ask a Chinese person where a Chinese restaurant is? I mean, aren''t we all getting a little too sensitive? I mean, somebody asks me which way is Israel, I don''t fly off the handle.', 'Jerry', 5, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can’t believe how easy it is. I’m virtually Orthodox. All I have to do is read a few books, memorize a few prayers, and I’m in the club.', 'George', 5, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('She told me. She said she’s never had a man stir up all of these feelings inside of her. She’s questioning her faith. She’s thinking of leaving the church. Oh, uh, this power. I’m dangerous Jerry, I’m very very dangerous!', 'Kramer', 5, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Elaine, he''s a male bimbo. He''s a mimbo!', 'Jerry', 5, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s a different world when you''re with a cool guy.', 'George', 5, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('No, I don''t have a square to spare. I can''t spare a square.', 'Jane', 5, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The key to eating a black and white cookie, Elaine, is you want to get some black and some white in each bite. Nothing mixes better than vanilla and chocolate. And yet, still, somehow racial harmony eludes us. If people would only look to the cookie. All our problems would be solved.', 'Jerry', 5, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Nobody takes better care of their hair than me. You can serve dinner on my head.', 'Elaine', 5, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Why couldn''t you make me an architect? You know I always wanted to pretend that I was an architect.', 'George', 5, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('So I started to walk into the water. I won''t lie to you boys, I was terrified. But I pressed on, and as I made my way past the breakers a strange calm came over me. I don''t know if it was divine intervention or the kinship of all living things, but I tell you Jerry, at that moment I was a marine biologist.', 'George', 5, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The sea was angry that day, my friends, like an old man trying to send back soup in a deli.', 'George', 5, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This woman is bending my mind into a pretzel.', 'Jerry', 5, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Did you just roll your eyes at him? Because let me tell you something. If anybody should be rolling their eyes, it is me, at him, about you.', 'Elaine', 5, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If I was a woman I''d be down on the dock waiting for the fleet to come in.', 'Jerry', 5, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I spend so much time trying to get their clothes off, I never thought of taking mine off.', 'George', 5, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, George, they''re doing wonderful things at mental institutions these days. I''d be happy to set up a meet and greet.', 'Jerry', 5, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m really enjoying this marriage thing. You think about each other, you care about each other. It''s wonderful. Plus, I love saying ''my wife''. Once I started saying it, I couldn''t stop. ''My wife'' this, ''My wife'' that. It''s an amazing way to begin a sentence.', 'Jerry', 5, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I guess I just wasn''t ready for the responsibilities of a pretend-marriage.', 'Jerry', 5, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey, believe me, baldness will catch on. When the aliens come, who do you think they''re gonna relate to? Who do you think''s gonna be the first ones getting a tour of the ship?', 'George', 5, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Booing and hissing are not part of the show. You boo puppets. You hiss villains in silent movies.', 'Jerry', 5, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Is it me, or was that the ugliest baby you have ever seen?', 'Jerry', 5, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Like when a man goes swimming... Afterwards...', 'George', 5, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Look, you don''t understand. There was shrinkage.', 'George', 5, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Elaine, don''t get too down. Everything will even out. See, I have two friends. You were up, he was down. Now he''s up, you''re down. You see how it all evens out for me?', 'Jerry', 5, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Bald men with no jobs and no money who live with their parents don''t approach strange women.', 'George', 5, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh. I''m watching my height. My doctor doesn''t want me to get any taller.', 'Jerry', 6, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Generally speaking, you don''t need any extra incentive to murder a dry cleaner.', 'Jerry', 6, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Newman never stops seeing anybody. Newman will see whoever is willing to see him.', 'Jerry', 6, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Where are the totebags? I''m not leaving the premises without totebags. I was promised totebags and totebags I shall have.', 'Kramer', 6, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I saw someone on the street eating M&M''s with a spoon.', 'Jerry', 6, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If I like their race, how can that be racist?', 'Jerry', 6, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m out there Jerry and loving every minute of it.', 'Jerry', 6, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s a shame his parents didn''t get divorced thirty years ago. He could''ve been normal.', 'Jerry', 6, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I need the secure packaging of Jockeys. My boys need a house!', 'Kramer', 6, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The only thing between him and us is a thin layer of gaberdine.', 'Jerry', 6, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what I love? How there''s two nuts named after people: Hazel and Filbert.', 'George', 6, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('So let me get this straight. You find yourself in the kitchen, you see an eclair in the receptacle, and you think to yourself, ''What the hell, I''ll just eat some trash.''', 'Jerry', 6, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Horse manure''s not that bad. I don''t even mind the word manure. It''s newer, which is good, and a ma in front of it. Ma-Newer. When you consider the other choices, manure is actually pretty refreshing.', 'George', 6, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I really like depriving myself of things. It''s fun! Very monastic.', 'Kramer', 6, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What''s so great about a mom and pop store? Let me tell you something, if my mom and pop ran a store I wouldn''t shop there.', 'George', 6, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('For all I know, this guy went out of his way to not invite you. How am I going to feel if I show up with an uninvited, unwelcome intruder?', 'George', 6, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I would give up red meat just to get a glimpse of you in a bra.', 'George', 6, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yes, this is a business office, but I''m not a businessman per se. I''m here working for the people. I''m causing dissent, stirring the pot, getting people to question the whole rotten system.', 'Jerry', 6, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Fine, you want to be a communist, be a communist. Can''t you at least look like a successful communist?', 'Elaine', 6, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('All my life I''ve been running away from that name. That''s why I wouldn''t tell anybody. But I''ve been thinking about it. All this time I''m trying not to be me. I''m afraid to face who I was. But I''m Cosmo, Jerry, I''m Cosmo Kramer, and that''s who I''m going to be. From now on, I''m Cosmo!', 'Kramer', 6, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Do you ever just get down on your knees and thank God that you know me and have access to my dementia?', 'George', 6, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The jokes kept bouncing off her like Superman.', 'Jerry', 6, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I would drape myself in velvet if it were socially acceptable.', 'George', 6, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Alright, fine, you sit there and you watch while Newman takes over the world. But he''d be a horrible leader. And you know who''s going to suffer? The little people. You and George.', 'Kramer', 6, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t trust this guy. I think he re-gifted, and then he de-gifted, and now he''s using an upstairs invite as a springboard to a Super Bowl sex romp.', 'Jerry', 6, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what the Ukraine is? It''s a sitting duck. A road apple, Newman. The Ukraine is weak. It''s feeble. I think it''s time to put the hurt on the Ukraine.', 'George', 6, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('When someone is lying, is it true that their pants are actually on fire?', 'Jerry', 6, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I feel like my old self again... Totally inadequate, completely insecure, paranoid, neurotic... It''s a pleasure.', 'George', 6, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I got rejected by a bald woman.', 'George', 6, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, frankly, outside of a sexual relationship, I don''t see the point to it. I''m not thrilled with all the handshaking either, but one step at a time.', 'Jerry', 6, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('No, no, a bra is for ladies. Meet the Bro!', 'Kramer', 6, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('He''s a comedian, Mrs. Payton. They don''t know how to do anything.', 'Elaine', 6, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Say you''re getting intimate with a woman, you don''t want her fumbling and struggling back there. I think we''ve all experienced that.', 'Kramer', 6, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('See, the thing of it is, there''s a lot of ugly people out there walking around but they don''t know they''re ugly because nobody actually tells them.', 'Jerry', 6, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m grotesque. I look like a troll.', 'George', 6, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('All those mechanics do is work all day with their hands and their big muscular arms on machines and then they come home dripping with animal sexuality like Stanley Kowalski. What a huge turn-off that is.', 'Elaine', 6, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('We were in the garage. You know how garages are. They''re conducive to sex talk. It''s a high testosterone area.', 'Jerry', 6, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m Cosmo Kramer, the Assman!', 'Kramer', 6, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Have you ever met a proctologist? They usually have a very good sense of humor. You meet a proctologist at a party, don''t walk away. Plant yourself there because you will hear the funniest stories you''ve ever heard. See, no one wants to admit to them that they stuck something up there. Never. It''s always an accident. Every proctologist story ends in the same way... ''It was a million to one shot, doc, million to one.''', 'Kramer', 6, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah, but before I met up with her, I stopped to look at the monkeys, when all of a sudden I am hit in the face with a banana peel. I turn and look and there is this monkey really laughing it up. Then someone tells me that he did it. Well, I pick up the banana peel and I wait for that monkey to turn around. And then I *whap* let him have it.', 'Kramer', 6, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Kramer, you threw a banana peel at a monkey?', 'Jerry', 6, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah, white meat. And if I see one piece of dark meat on there. It''s your ass buster.', 'Kramer', 6, 24);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m much more comfortable criticizing people behind their backs.', 'George', 7, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It can never be erased. It''ll follow us wherever we go for the rest of our lives. I''ll never be able to get a job. I mean, doesn''t that concern you? Everything I''ve worked for...down the drain because of one stupid mistake. I mean, aren''t we entitled to make one mistake in our lives, Jerry?', 'Kramer', 7, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('In your situation the only sex you''re going to have better than make-up sex is if you''re sent to prison and you have a conjugal visit.', 'Jerry', 7, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah that''s going to be a problem. It''s gonna be a problem for them. This a clear violation of your rights as a consumer. It''s an infringement on your constitutional rights. It''s outrageous, egregious, preposterous.', 'Jackie', 7, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You put the balm on? Who told you to put the balm on? I didn''t tell you to put the balm on. Why''d  you put the balm on? You haven''t even been to see the doctor. If your gonna put a balm on, let a doctor put a balm on.', 'Jackie', 7, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''d rather be dating the blind. You know, you could let the house go. You could let yourself go. A good looking blind woman doesn''t even know you''re not good enough for her.', 'George', 7, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('When you look annoyed all the time, people think that you''re busy.', 'George', 7, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('We all get a little cuckoo sometimes, George. I used to be like you. Berating personnel until they cried, calling managers on the field during a game, threatening to move the team to New Jersey, just to upset people. Then I found a way to relax. I''ve got two words to say to you, George... Hot Tub!', 'George Steinbrenner', 7, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You can''t eat this soup standing up, your knees buckle.', 'George', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The guy who runs the place is a little temperamental, especially about the ordering procedure. He''s secretly referred to as the Soup Nazi.', 'Jerry', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('No soup for you!', 'The Soup Nazi', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('He''s not a Nazi. He just happens to be a little eccentric. Most geniuses are.', 'Kramer', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('So, essentially, you chose soup over a woman?', 'Elaine', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You''re through, Soup Nazi. Pack it up. No more soup for you. Next!', 'Elaine', 7, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('There''s nothing more pathetic than a grown man who''s afraid of a woman.', 'Kramer', 7, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('This is totally different! That was my secret, this is Jerry''s secret! There''s...there''s attorney-client priveleges here! If I play it by your rule, no one''ll ever confide in me again, I''ll be cut out of the loop!', 'George', 7, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, you know, I was thinking about what you said before, and...you''re right, I''ve never really been a couple, so...if that''s the rule, then I''m gonna go by the rule.', 'Kramer', 7, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Elaine...let me just explain something to you. See, this is not just a weekend routine...I''m on the verge of make-up sex here. You know about make-up sex?', 'George', 7, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I mean, she''s giving and caring and genuinely concerned about the welfare of others - I can''t be with someone like that!', 'Jerry', 7, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah, it was, but then I just couldn''t decide if he was really sponge-worthy.', 'Elaine', 7, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Now see, this is what the holidays are all about. Three buddies sitting around, chewing gum.', 'Kramer', 7, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I think I finally figured out what the flavor is in this gum. It''s a little lo-meiny.', 'Jerry', 7, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, why go to a fine restaurant when you could just stick something in the microwave... Why go to the park and fly a kite when you could just pop a pill?', 'George', 7, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t want John thinking that I''m hot and heavy if he''s not hot and heavy. I''m trying to get a little squirrel to come over to me here. I don''t want to make any big sudden movements. I''ll frighten him away.', 'Elaine', 7, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Let me understand. You''ve got the hen, the chicken and the rooster. The rooster goes with the chicken. So, who''s having sex with the hen?', 'Frank Costanza', 7, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Have I ever bought you a jockstrap as a gift?', 'Jerry', 7, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('A woman just walking around in broad daylight with nothing but a bra on? She''s a menace to society.', 'Elaine', 7, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s lewd, lascivious, salacious, outrageous!', 'Jackie', 7, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I miss the days when they made toys that could kill a kid.', 'Jerry', 7, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well, I was under the impression that I could take anything I wanted from your fridge, and you could take whatever you want from mine.', 'Kramer', 7, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('A wise man once taught me the healing power of the body''s natural pressure points. He sells t-shirts outside the World Trade Center.', 'Kramer', 7, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I have never been anyone''s type, but apparently, this Marisa Tomei loves funny, quirky, bald men.', 'George', 7, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m not force-feeding myself a steak at four-thirty to save a couple of bucks, I''ll tell you that!', 'Jerry', 7, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If I don''t have a good shower, I am not myself. I feel weak and ineffectual. I''m not Kramer.', 'Kramer', 7, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s disgusting. I''m sitting there in a tepid pool of my own filth. All kinds of microscopic parasites and organisms having sex all around me.', 'Kramer', 7, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Look at you, you''re disgusting. You''re bald, you''re paunchy. All kinds of sounds are emanating from your body twenty-four hours a day. If there''s a woman that can take your presence for more than ten consecutive seconds, you should hang on to her like grim death... which is not far off by the way.', 'Jerry', 7, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Now this is remarkable. I''m lounging, and yet, my pants remain perfectly creased.', 'Kramer', 7, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh, I''m percolating, Jerry. I''m telling you, I have never felt so fertile. I''m mossy, Jerry. My brain is mossy. Listen to this idea. A restaurant that serves only peanut butter and jelly.', 'Kramer', 7, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I don''t know! (building to a shout) But I woke up in the Hudson river in a SACK!! I think she drugged me, but she''s a murderer and I''m calling the cops.', 'Kramer', 7, 87);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s been known to happen....... telling you right now Elaine, this guy ''s gonna dangle that dress in front of you like a dirt farmer dangles a carrot in front of a mule.', 'Jerry', 7, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I am never putting on another piece of clothing unless it''s straight out of the dryer.', 'Kramer', 7, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Let me be perfectly blunt. I don''t care for you, Costanza. You hang out on the west side of the building with Seinfeld all day laughing it up, wasting your lives.', 'Newman', 7, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You''ve got your shirt in my oven?', 'Jerry', 7, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey. You put your groceries under the hood of my car?', 'Jerry', 7, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('A mechanic forms an emotional attachment, thinks he''s gonna lose the car, he panics, he does something rash. I''m gonna ask you somepersonal questions. I''m sorry if I touch a nerve, but I think it''ll help with the case. Had you been taking good care of the car?', 'The Detective(After Jerry''s mechanic steals his car.)', 7, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah, don''t worry Jerry. We''re right on this guy like stink on a monkey! I''ll check back with you.', 'Kramer', 7, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Ah, look, I..I''m sorry to bother you, but I''m a US postal worker and my mail truck was just ambushed by a band of backwoods mail-hating survivalists.', 'Newman', 7, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can''t get my pants off, and Mickey''s audition is in twenty minutes! You know, I''m supposed to be a business man, I gotta be in costume!', 'Kramer', 7, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey!! Buddy. I thought of a great invention for driving. A periscope in a car, so you can see the traffic.', 'Kramer', 7, 23);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I was free and clear. I was living the dream. I was stripped to the waist eating a block of cheese the size of a car battery.', 'George', 8, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Between you and me, I always thought Kramer was a bit of a doofus. But, he believed in me. You did not. So, as I see it, he''s not the doofus. You are the doofus.', 'Elaine', 8, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh, she''s uh...she''s real. She can bring home the bacon and fry it in the pan.', 'Kramer', 8, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can''t spend the rest of my life coming into this stinking apartment every ten minutes to pore over the excruciating minutia of every single daily event.', 'Elaine', 8, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('She had man-hands!', 'Jerry', 8, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Women like that are like members of a secret tribe living in a forbidden city. People like me have not been inside in thousands of years.', 'George', 8, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what they say, ''You don''t sell the steak, you sell the sizzle.''', 'Kramer', 8, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It''s more like a full-body dry heave set to music.', 'George', 8, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Who''s going to bomb you? An airline? For all the stupid little peanut jokes?', 'George', 8, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know what? I can''t do this. I can''t read books anymore; books on tape have ruined me, Jerry. I need that nice voice. This book has *my* voice. I hate my voice.', 'George', 8, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Well I also dropped it on the way over. Look I''m in trouble, I got no skills. I can''t peel, I can''t chop, I can''t grate. I can''t mince! I got no sense of flavor, obviously. You know, I gotta talk to Frank.', 'Kramer', 8, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Why do they call it Ovaltine? The mug is round. The jar is round. They should call it round tine. That''s gold, Jerry! Gold!', 'Banya', 8, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Here you''re just another apple. But in Japan, you''re an erotic fruit. Like an orange, which is rare there.', 'Kramer', 8, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''m like a commercial jingle. First it''s a little irritating. Then you hear it a few times. You''re humming it in the shower. By the third date, it''s ''Buy Mennen!''', 'George', 8, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can do six weeks standing on my head. I''m a sexual camel.', 'George', 8, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('To a woman, sex is like the garbage man. You just take for granted the fact that any time you put some trash out on the street, a guy in a jumpsuit''s gonna come along and pick it up. But now, it''s like a garbage strike. The bags are piling up in your head. The sidewalk is blocked. Nothing''s getting through. You''re stupid.', 'Jerry', 8, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Guys, hitting is not about muscle. It''s simple physics. Calculate the velocity, v, in relation to the trajectory, t, in which g, gravity, of course remains a constant. It''s not complicated.', 'George', 8, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Newman is my sworn enemy. And he lives down the hall from my home. My home, Elaine! Where I sleep, where I come to play with my toys.', 'Jerry', 8, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('A bird ran into my giant freak-head.', 'Elaine', 8, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I couldn''t get there in time to stop it, but you should have seen Little Jerry, Jerry! Flappin'' his wings and struttin'' his stuff! He was peckin'' and weavin'' and bobbin'' and talkin'' trash! He didn''t even have to touch him! The other rooster ran out of the ring. The whole fight lasted two seconds.', 'Jerry', 8, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Yeah. Hey Jerry, listen to this. I discovered something even better than conjugal visit sex. Fugitive sex!', 'George', 8, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('George, this is a little too much for me - escaped convicts, fugitive sex...I got a cockfight to focus on.', 'Jerry', 8, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The jerk store called, they''re running out of you!', 'George', 8, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, George, the ocean called. They''re running out of shrimp.', 'Riley', 8, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I slipped - and fell in the mud. Ruining the very pants I was about to return.', 'Kramer', 8, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Oh, I bought a bunch of bunion stories from Newman - but they all stink!', 'Kramer', 8, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('My whole life I have never made a great entrance.', 'George', 8, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('That stuff is unbelievable. I''d eat it out of a dumpster.', 'Kramer', 8, 16);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('These Dominicans really know their way round a crepe. Look at that.It''s like they''re rolling a double corona.', 'Kramer', 8, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I love a good nap. Sometimes it''s the only thing getting me out of bed in the morning.', 'George', 8, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Listen to this. Marcy comes over and she tells me that her ex-boyfriend was over late last night and ''yada yada yada I''m really tired today.'' You don''t think she''d yada yada sex?', 'George', 8, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Come celebrate the millennium, with Newmanniun. Newman!', 'Kramer', 8, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('For me, the next millennium must be Jerry-free.', 'Newman', 8, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, if you take everything I''ve done in my entire life and condense it down into one day, it looks decent.', 'George', 8, 21);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Because men think if women are grabbing and clawing at each other, there''s a chance they might somehow kiss.', 'Kramer', 8, 22);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I feel like an out-of-work porn star.', 'George', 9, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Boy, a month in Europe with Elaine. That guy''s coming home in a body bag.', 'Kramer', 9, 1);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Breaking up is like knocking over a Coke machine. You can''t do it in one push. You gotta rock it back and forth a few times, and then it goes over.', 'Jerry', 9, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You know, Darren, if you had told me twenty-five years ago that some day I''d be standing here about to solve the world''s energy problems, I would''ve said you were crazy. Now let''s push this giant ball of oil out this window.', 'Kramer', 9, 2);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Serenity now, insanity later.', 'Lloyd Brawn', 9, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('George, letting my emotions out was the best thing I''ve ever done. Sure, I''m not funny anymore, but there''s more to life than making shallow, fairly obvious observations.', 'Jerry', 9, 3);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Food and sex. Those are my two passions. It''s only natural to combine them.', 'George', 9, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Now if you''ll excuse me, I have to go fill my freezer with my own blood.', 'Kramer', 9, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I can feel his blood inside of me. Borrowing things from my blood.', 'Kramer', 9, 4);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('No Chinese leftovers. George is gettin'' suspicious.', 'George', 9, 5);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Wait a minute. You mean to say that you drugged a woman so you could take advantage of her toys?', 'Kramer', 9, 6);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I haven''t had a decent sandwich in thirteen years.', 'Kramer', 9, 7);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You can stuff your sorries in a sack, mister!', 'George', 9, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Why not? We''re neighbors. What''s mine is yours.', 'Jerry', 9, 8);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('But the thing you don''t realize is that there''s good naked and bad naked. Naked hair brushing - good. Naked crouching - bad.', 'Jerry', 9, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('The female body is a work of art. The male body is utilitarian. It''s for gettin'' around. It''s like a Jeep.', 'Elaine', 9, 9);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('At the Festivus dinner, you gather your family around and tell them all the ways they have disappointed you over the past year.', 'Frank Costanza', 9, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('It was destroyed. But out of that a new holiday was born... A Festivus for the rest of us!', 'Frank Costanza', 9, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Stop crying and fight your father!', 'Frank Costanza', 9, 10);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Slapping hands is the lowest form of primate ritual.', 'Jerry', 9, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I think I''ve reached a point in my life where I can tell the difference between nougat and cookie.', 'George', 9, 11);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Nobody carries wallets anymore. They went out with powdered wigs.', 'Kramer', 9, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Hey Silvio, look at Jerry here, prancing around in his coat with his purse. Yup, he''s a dandy. He''s a real fancy boy!', 'Jerry', 9, 12);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('She does stink. And she should quit. But I don''t want it to be because of me. It should be the traditional route. Years of rejection and failure until she''s spit out the bottom of the porn industry.', 'Jerry', 9, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What do I need to talk for, huh? What, to blab to the neighbors about how George has a new femme Jerry friend? To tell everybody at the coffee shop how George is all mixed up in a perverse sexual amalgam of some girl and his best friend? See now, I''ve done all that. Now it''s time for silence.', 'Kramer', 9, 13);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Man''s Best Friend... Jerry, I want something like that on my tombstone.', 'Kramer', 9, 14);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Kramer, you can''t live down here. This is where people come to die.', 'Jerry', 9, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('I''ve been lying about my income for a few years. I figured I could afford a fake house in the Hamptons.', 'George', 9, 15);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('If it wasn''t for the toilet, there would be no books.', 'George', 9, 17);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('What is nice? Trying to fill the void in your life with flour and sugar and egg and vanilla? I mean, we are all unhappy. Do we have to be fat too?', 'Elaine', 9, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Kramer, listen to me. I''m never going to have a child. If I lose this Frogger high score, that''s it for me.', 'George', 9, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('She''s a sentence finisher. It''s like dating Mad Libs.', 'Jerry', 9, 18);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('There''s nothing more sophisticated than diddling the maid and then chewing some gum.', 'Elaine', 9, 19);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('You''ve got insurance. You tell them that the car was stolen, and then you get another one free.', 'Kramer', 9, 20);
INSERT INTO seinfeld_quotes (quote, author, season, episode) VALUES ('Uh, yes, most likely, yes. I''m, uh, H.E. Pennypacker. I''m a wealthy industrialist and philanthropist and, uh, a bicyclist. And, um, yes, I''m looking for a place where I can settle down with my, uh, peculiar habits, and, uh, the women that I frequent with.', 'Kramer', 9, 20);

-- Total records inserted: 333

-- Verify the data
SELECT COUNT(*) FROM seinfeld_quotes;
SELECT * FROM seinfeld_quotes LIMIT 5;